# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = 'maier/centos-7.2.1511-x86_64'
    config.vm.provision 'shell', inline: <<-SHELL
        echo "Updating yum cache"
        yum -q -e 0 makecache fast
        echo "Installing RPM building utilities"
        yum -q install -y rpmdevtools
        su - vagrant -c rpmdev-setuptree
    SHELL
end
