---
- hosts: all
  vars:
    # update when src/package.json version bumped and ready for release
    cosi_site_version: "2.4.0"
    # if using omnios, ensure node_version is built and appropriate node and
    # modules tgz's are placed in roles/{site,node}/files directories
    # respectively.
    node_version: "4.4.5"
    # note, **just** the file name, not a "path" the specified file is expected
    # to be in ./content/files relative to cosi-site.js
    installer_rpm_file: "cosi-{{ cosi_site_version }}-1.noarch.rpm"
  roles:
    - os
    - node
    - site
