---

- name: Load common role variables
  include_vars: "../vars/common.yml"

- name: Check directory
  become: true
  file: path="{{ node_directory }}/bin" state=directory owner="{{ node_owner }}" group="{{ node_group }}" mode=0755

- name: Load OS specific role variables
  include_vars: "{{ item }}"
  with_first_found:
      - files:
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          - "../vars/{{ ansible_distribution }}.yml"
          - "../vars/{{ ansible_os_family }}.yml"
          - "../vars/{{ ansible_system }}.yml"
        skip: true

- name: Install
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"

#
# set the locations of node and npm as facts (used in site role)
# verify node and npm are actually installed
#
- name: Set node_bin
  set_fact: node_bin="{{ node_directory }}/bin/node" state=file

- name: Stat node_bin
  stat: path="{{ node_bin }}"
  register: st

- name: Verify node_bin
  fail: "Node binary not found {{ node_bin }}"
  when: st.stat.exists is not defined or st.stat.exists == false

- name: Set npm_bin
  set_fact: npm_bin="{{ node_directory }}/bin/npm" state=file

- name: Stat npm_bin
  stat: path="{{ npm_bin }}"
  register: st

- name: Verify npm_bin
  fail: "NPM binary(link) not found {{ npm_bin }}"
  when: st.stat.islnk is not defined or st.stat.islnk == false
