---

#node_version: "8.9.4"
node_version: "4.4.5"

#
# the base directory where binaries are expected to be in ./bin. e.g.
#   {{ node_directory }}/bin/node
#   {{ node_directory }}/bin/npm
#
node_directory: /opt/circonus

# default owner/group of {{ node_directory }}/bin
node_owner: root
node_group: root
