---

- debug: msg="OS {{ ansible_os_family }} {{ ansible_distribution }} v{{ ansible_distribution_version }} {{ ansible_userspace_architecture }}"

- name: Common variables
  include_vars: "../vars/common.yml"

- name: Common tasks
  import_tasks: "common.yml"

- name: OS Specific variables
  include_vars: "{{ item }}"
  with_first_found:
      - files:
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          - "../vars/{{ ansible_distribution }}.yml"
          - "../vars/{{ ansible_os_family }}.yml"
          - "../vars/{{ ansible_system }}.yml"
        skip: true

- name: OS Specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_distribution }}.yml"
          - "{{ ansible_os_family }}.yml"
          - "{{ ansible_system }}.yml"
        skip: true
