# -*- mode: ruby -*-
# vi: set ft=ruby :
# rubocop:disable Metrics/BlockLength

require 'digest/sha1'
site_ip = '192.168.100.10'

Vagrant.configure(2) do |config|
    #
    # cosi-site
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-site")[0..8]
    config.vm.define 'site' do |site|
        site.vm.box = 'maier/centos-7.2.1511-x86_64'
        site.vm.hostname = "cosi-site-#{host_sig}"
        site.vm.network 'private_network', ip: site_ip
        # leverage main 'cosi-site' ansible playbook
        site.vm.provision 'ansible' do |ansible|
            # ansible.verbose = 'vvvv'
            ansible.compatibility_mode = '2.0'
            ansible.playbook = '../provision/cosi-site.yml'
        end
    end

    #
    # client node(s)
    #

    #
    # CentOS
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-c6")[0..8]
    config.vm.define 'c6', autostart: false do |c6|
        c6.vm.box = 'maier/centos-6.8-x86_64'
        c6.vm.hostname = "cosi-c6-#{host_sig}"
        c6.vm.network 'private_network', ip: '192.168.100.11'
        c6.vm.provision 'shell', inline: <<-SHELL
            # add alias for setup.circonus.com, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            yum -q -e 0 makecache fast
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-c7")[0..8]
    config.vm.define 'c7', autostart: false do |c7|
        c7.vm.box = 'maier/centos-7.3.1611-x86_64'
        c7.vm.hostname = "cosi-c7-#{host_sig}"
        c7.vm.network 'private_network', ip: '192.168.100.12'
        c7.vm.provision 'shell', inline: <<-SHELL
            # add alias for setup.circonus.com, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            yum -q -e 0 makecache fast
            echo
            echo "Installing Agent POST hook script for CentOS7"
            mkdir -pv /opt/circonus/cosi
            cp -v /vagrant/hooks/c7/agent_post_hook.sh /opt/circonus/cosi
            chmod -v 755 /opt/circonus/cosi/agent_post_hook.sh
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # Ubuntu
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-u14")[0..8]
    config.vm.define 'u14', autostart: false do |u14|
        u14.vm.box = 'maier/ubuntu-14.04-x86_64'
        u14.vm.hostname = "cosi-u14-#{host_sig}"
        u14.vm.network 'private_network', ip: '192.168.100.21'
        u14.vm.provision 'fix-no-tty', type: 'shell' do |s|
            s.privileged = false
            s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
        end
        u14.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-u16")[0..8]
    config.vm.define 'u16', autostart: false do |u16|
        u16.vm.box = 'maier/ubuntu-16.04-x86_64'
        u16.vm.hostname = "cosi-u16-#{host_sig}"
        u16.vm.network 'private_network', ip: '192.168.100.22'
        u16.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
        u16.vm.provider 'virtualbox' do |vb|
            vb.name = "cosi-u16-#{host_sig}"
            # disable creation of the boot console log in host's directory
            vb.customize ['modifyvm', :id, '--uartmode1', 'disconnected']
        end
        u16.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # OmniOS
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-r151014")[0..8]
    config.vm.define 'omnios', autostart: false do |omnios|
        omnios.vm.box = 'maier/omnios-r151014-x86_64'
        omnios.vm.hostname = "cosi-omnios-#{host_sig}"
        omnios.vm.network 'private_network', ip: '192.168.100.31'
        omnios.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo "Installing Agent POST hook script"
            mkdir -pv /opt/circonus/cosi
            cp -v /vagrant/hooks/omnios/agent_post_hook.sh /opt/circonus/cosi
            chmod -v 755 /opt/circonus/cosi/agent_post_hook.sh
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # Oracle Linux
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-ol72")[0..8]
    config.vm.define 'ol72', autostart: false do |ol72|
        ol72.vm.box = 'boxcutter/ol72'
        ol72.vm.hostname = "cosi-ol72-#{host_sig}"
        ol72.vm.network 'private_network', ip: '192.168.100.41'
        ol72.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # Debian 7.11 (wheezy)
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-d7")[0..8]
    config.vm.define 'deb7', autostart: false do |d7|
        d7.vm.box = 'maier/debian-7.11.0-x86_64'
        d7.vm.hostname = "cosi-d7-#{host_sig}"
        d7.vm.network 'private_network', ip: '192.168.100.51'
        d7.vm.provision 'fix-no-tty', type: 'shell' do |s|
            s.privileged = false
            s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
        end
        d7.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # Debian 8.7 (jessie)
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-d8")[0..8]
    config.vm.define 'deb8', autostart: false do |d8|
        d8.vm.box = 'maier/debian-8.7.0-x86_64'
        d8.vm.hostname = "cosi-d8-#{host_sig}"
        d8.vm.network 'private_network', ip: '192.168.100.52'
        d8.vm.provision 'fix-no-tty', type: 'shell' do |s|
            s.privileged = false
            s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
        end
        d8.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # Debian 9.1 (stretch)
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-d9")[0..8]
    config.vm.define 'deb9', autostart: false do |d9|
        d9.vm.box = 'maier/debian-9.1.0-x86_64'
        d9.vm.hostname = "cosi-d9-#{host_sig}"
        d9.vm.network 'private_network', ip: '192.168.100.53'
        d9.vm.provision 'fix-no-tty', type: 'shell' do |s|
            s.privileged = false
            s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
        end
        d9.vm.provision 'shell', inline: <<-SHELL
            # add alias for cosi-site, so it will "resolve"
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end

    #
    # FreeBSD
    #
    host_sig = Digest::SHA1.hexdigest("#{`hostname`}-cosi-bsd11")[0..8]
    config.vm.define 'bsd11', autostart: false do |bsd11|
        bsd11.vm.guest = :freebsd
        # mac not set in base box, just needs to be set to something to avoid vagrant errors
        bsd11.vm.base_mac = ''
        bsd11.ssh.shell = 'sh'
        bsd11.vm.box = 'freebsd/FreeBSD-11.0-RELEASE-p1'
        bsd11.vm.hostname = "cosi-bsd11-#{host_sig}"
        bsd11.vm.network 'private_network', ip: '192.168.100.61'
        bsd11.vm.synced_folder '.', '/vagrant', id: 'vagrant-root', disabled: true
        bsd11.vm.provider 'virtualbox' do |vb|
            vb.name = 'bsd11'
            vb.customize ['modifyvm', :id, '--memory', '2048']
            vb.customize ['modifyvm', :id, '--cpus', '2']
            vb.customize ['modifyvm', :id, '--hwvirtex', 'on']
            vb.customize ['modifyvm', :id, '--audio', 'none']
            vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
            vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
        end
        bsd11.vm.provision 'shell', inline: <<-SHELL
            pkg install -y -q bash curl
            echo "#{site_ip} cosi-site" >> /etc/hosts
            echo " "
            echo " "
            echo "run: [ curl 'http://cosi-site/install' | bash -s -- --key ... --app ... --cosiurl 'http://cosi-site/' ]"
            echo ">>>>> API KEY REQUIRED!!!"
            echo ">>>>> API APP REQUIRED!!!"
            echo ">>>>> --cosiurl points to the 'site' VM created above, elide to use the default (https://onestep.circonus.com)"
            echo "Obtain valid API key and app values from https://login.circonus.com/user/tokens -- click (i) next to the token to use"
            echo " "
            echo " "
        SHELL
    end
end
